---

- name: setup
  include: setup_{{ansible_os_family}}.yml

- name: method
  include: "provider-{{ certificate_provider }}.yml"

# - name: info
#   command: openssl x509 -text -noout
#     -in "{{ certificate_file }}"
#   changed_when: false
#   register: _certificate_info
#
# - debug:
#     msg: "{{ _certificate_info.stdout_lines }}"
